import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { v2 as cloudinary } from "cloudinary";
import { ToastProvider } from "@/providers/toast-provider";

// Components
import SideBar from "@/components/sidebar/SideBar";
cloudinary.config({
  cloud_name: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${inter.className} bg-slate-100 overflow-hidden`}>
        <ToastProvider />
        <div className="h-full overflow-hidden">
          <SideBar />
          <main className="h-full pl-24 lg:pl-72">
            <div className="h-full overflow-y-auto">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
